### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by abd-bourai** [aws/aws-lambda-python-runtime-interface-client#19]
Hi,

i'm seeing:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/av.runfiles/__main__/awslambdaric/__main__.py", line 21, in <module>
    main(sys.argv)
  File "/av.runfiles/__main__/awslambdaric/__main__.py", line 17, in main
    bootstrap.run(app_root, handler, lambda_runtime_api_addr)
  File "/av.runfiles/__main__/awslambdaric/bootstrap.py", line 432, in run
    log_sink,
  File "/av.runfiles/__main__/awslambdaric/bootstrap.py", line 188, in handle_event_request
    log_error(error_result, log_sink)
  File "/av.runfiles/__main__/awslambdaric/bootstrap.py", line 139, in log_error
    log_sink.log_error(error_message_lines)
  File "/av.runfiles/__main__/awslambdaric/bootstrap.py", line 323, in log_error
    sys.stdout.write(error_message)
  File "/av.runfiles/__main__/awslambdaric/bootstrap.py", line 300, in write
    self.stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 547-548: ordinal not in range(128)
```

when running test requests to my lambda. my python version in the docker image is 3.6.9

**Comment by Furriz844** [comment]
Have this issue too.

**Comment by Furriz844** [comment]
@abd-bourai, try to add this enviroment PYTHONIOENCODING="utf8"
it works for me.

**Comment by ewengillies** [comment]
also getting this error, it feels like a python 2 vs python 3 thing, but we're definitely using python3.  Unfortunately, its an intermittent error, happens sometimes, other times it doesn't.

> @abd-bourai, try to add this enviroment `PYTHONIOENCODING="utf8"`
> it works for me.

this totally works, but the error itself is a little unsettling, especially since its intermittent thus not super reproducable.  Any ideas on why this is happening?

**Comment by rush86999** [comment]
how do you set this value in a docker file with an entrypoint 
```
ENTRYPOINT ["python3", "-m", "awslambdaric"]
```

**Comment by Furriz844** [comment]
@rush86999 , Hi!
Just put it into your dockerfile:
`ENV PYTHONIOENCODING="utf8"` 
Or when you run your image, you can set variable by command:
`docker run -e "PYTHONIOENCODING=utf8" %image_id%`
