### ISSUE TITLE
The Dockerfile written in README does not work

### ISSUE THREAD

**Issue by gorogoroyasu** [aws/aws-lambda-python-runtime-interface-client#6]
Thanks for this awesome project and I'm excited to use this app!!

By the way, I have some troubles to build my environment...
I followed the README.md on the project root (python part), and I couldn't execute the docker container.
I think there are two issues (or may be one) about it.

## AWS_LAMBDA_RUNTIME_API
First issue is the environment variable AWS_LAMBDA_RUNTIME_API is not shown in the README.
I searched this project and found `runtime:9001`, and `127.0.0.1:9001`, though they raises the following error...

## [ERROR] [1607095127222] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint

```
Executing 'app.handler' in function directory '/function'
[ERROR] [1607095127222] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/function/awslambdaric/__main__.py", line 21, in <module>
    main(sys.argv)
  File "/function/awslambdaric/__main__.py", line 17, in main
    bootstrap.run(app_root, handler, lambda_runtime_api_addr)
  File "/function/awslambdaric/bootstrap.py", line 416, in run
    event_request = lambda_runtime_client.wait_next_invocation()
  File "/function/awslambdaric/lambda_runtime_client.py", line 76, in wait_next_invocation
    response_body, headers = runtime_client.next()
RuntimeError: Failed to get next
```

This error could be related to the environment variable above, though I couldn't identify the problem.

I hope you to let me know If you can identify the reason why I couldn't build it.

Best.

**Comment by carlzogh** [comment]
Hey @gorogoroyasu, thanks for reaching out! :) 

`AWS_LAMBDA_RUNTIME_API` is set by a [Runtime API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html) and would be available for the Runtime Interface Client library to use when running either in Lambda as it is [1], or locally through the use of the [Runtime Interface Emulator](https://github.com/aws/aws-lambda-runtime-interface-emulator) [2].

[1]: Have you tried invoking your function in Lambda? (ref. https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) Lambda will run your image through the Runtime API and will invoke your function handler through the Runtime Interface Client.

[2]: Have you tried following the instructions under the [Local Testing](https://github.com/aws/aws-lambda-python-runtime-interface-client#local-testing) section of the README? This section describes how you would go about running your function packaged in a container image through the Runtime Interface Emulator (RIE). Another good reference here would be the AWS Documentation on [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html)

**Comment by gorogoroyasu** [comment]
Thanks for your quick response.
I misunderstood the document.
I was using it in local environment, so try your second suggestion!

**Comment by carlzogh** [comment]
Thanks! Closing - please feel free to reopen this issue or another if you encounter any other issues :)

**Comment by gorogoroyasu** [comment]
It worked pretty! thanks for your help! ❤️
