### ISSUE TITLE
LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint

### ISSUE THREAD

**Issue by Cpicon** [aws/aws-lambda-python-runtime-interface-client#8]
Hi guys!

I trying to test my container with awslambdaric but I am getting this error at the moment to execute app.handler

error:
```
[ERROR] [1607556612517] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/lang/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/task/awslambdaric/__main__.py", line 21, in <module>
    main(sys.argv)
  File "/var/task/awslambdaric/__main__.py", line 17, in main
    bootstrap.run(app_root, handler, lambda_runtime_api_addr)
  File "/var/task/awslambdaric/bootstrap.py", line 416, in run
    event_request = lambda_runtime_client.wait_next_invocation()
  File "/var/task/awslambdaric/lambda_runtime_client.py", line 76, in wait_next_invocation
    response_body, headers = runtime_client.next()
RuntimeError: Failed to get next
```

This is my Dockerfile:

`#Base image + runtime
FROM public.ecr.aws/lambda/python:3.7.2020.12.03.17

COPY requirements.txt /var/task/
#Install runtime interface client
RUN pip install --target  /var/task/ awslambdaric
RUN pip install -r requirements.txt -t /var/task/
#Copy files
COPY . /var/task/

#Add Lambda Runtime Interface Emulator and use a script in the ENTRYPOINT for simpler local runs
ADD aws-lambda-rie /usr/local/bin/aws-lambda-rie
RUN chmod 755 /usr/local/bin/aws-lambda-rie
RUN chmod 755 /tmp

EXPOSE 8080

ENTRYPOINT ["/var/task/entry.sh"]
RUN chmod 755 /var/task/entry.sh
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]`

The entrypoint is this:
```
#!/bin/sh
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
  exec /usr/local/bin/aws-lambda-rie /var/lang/bin/python -m awslambdaric app.handler
else
  exec /var/lang/bin/python -m awslambdaric app.handler
fi
```

my project is structured thus:

![Screen Shot 2020-12-09 at 19 31 56](https://user-images.githubusercontent.com/35033637/101705567-33c34b00-3a55-11eb-9af8-d8fb15ded0f6.png)

An this is my handler:

`from src.prediction import Inference

def handler(event, context):
    inference = Inference()
    prediction = inference.get(region= 'Nacional')

    return prediction
`
I built the image thus:

`docker build -t image_name:latest .`   

and run on this way:

` docker run  -p 9000:8080 image_name:latest`

the class inference just download the model from s3 and I set the ENV variables on .env file.

I am using pycharm and MacOS Big Sur. I am using python 3.7.

I will appreciate if you could help me with this issue, please.

**Comment by carlzogh** [comment]
Hey @Cpicon, thanks for reaching out!

I see from your Dockerfile that you're using the Lambda base image for Python 3.7:
```
FROM public.ecr.aws/lambda/python:3.7.2020.12.03.17
```

With Lambda base images you don't need the Runtime Interface Client as that's already pre-baked into the image. The Runtime Interface Emulator is too, so you also don't need to include that nor re-define the `ENTRYPOINT`.

As a side-note, I recommend not pinning your base image to a date-tagged Lambda base image to ensure you pull in the latest updates and security patches for Python 3.7 when they are released. You could use the `3.7` tag instead.

Your Dockerfile can then be simplified to:
```
FROM public.ecr.aws/lambda/python:3.7

COPY . /var/task/

RUN pip install -r requirements.txt -t /var/task/

EXPOSE 8080
CMD [ "app.handler" ] 
```

For more information about creating a function with AWS base images for Lambda check out https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-create-1

Please let us know if this works for you.

**Comment by Cpicon** [comment]
Thanks, I figured out. I noted that the tag version that I was using it is incompatible with the runtime importation that I was adding. Your solution is working. Thanks you so much!

**Comment by loretoparisi** [comment]
@carlzogh I have the same issue with this `Dockerfile` that I have to use because I cannot install `librosa` on CentOS / yum:

```Dockerfile
# Define function directory
ARG FUNCTION_DIR="/function"

FROM python:3.7.4-slim-buster as build-image

# librosa and ffmpeg dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    libsndfile1-dev \
    ffmpeg

# Install aws-lambda-cpp build dependencies
RUN apt-get update && \
  apt-get install -y \
  g++ \
  make \
  cmake \
  unzip \
  libcurl4-openssl-dev

# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Create function directory
RUN mkdir -p ${FUNCTION_DIR}

# Copy function code
COPY app.py ${FUNCTION_DIR}

# Install the runtime interface client
RUN pip install \
        --target ${FUNCTION_DIR} \
        awslambdaric

# Multi-stage build: grab a fresh copy of the base image
FROM python:3.7.4-slim-buster

# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the build image dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

EXPOSE 8080
ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "app.handler" ]
```

**Comment by umairamd** [comment]
@loretoparisi hi, were you able to solve this? getting something same for " public.ecr.aws/docker/library/python:3.10-alpine3.18" as final image
