### ISSUE TITLE
Command '['./scripts/preinstall.sh']' returned non-zero exit status 127

### ISSUE THREAD

**Issue by luthor2016ad** [aws/aws-lambda-python-runtime-interface-client#95]
Hello

in a Dockerfile:
From a alpine image
RUN pip install  awslambdaric
python setup.py egg_info did not run successfully.
#13 3.672   │ exit code: 1
#13 3.672   ╰─> [14 lines of output]
#13 3.672       *** Do not use buildconf. Instead, just use: autoreconf -fi
#13 3.672       ./buildconf: exec: line 4: autoreconf: not found
#13 3.672       Traceback (most recent call last):
#13 3.672         File "<string>", line 2, in <module>
#13 3.672         File "<pip-setuptools-caller>", line 34, in <module>
#13 3.672         File "/tmp/pip-install-oq3zcfna/awslambdaric_c7586fb4827e4213ae87abf6af43a2cc/setup.py", line 95, in <module>
#13 3.672           ext_modules=get_runtime_client_extension(),
#13 3.672         File "/tmp/pip-install-oq3zcfna/awslambdaric_c7586fb4827e4213ae87abf6af43a2cc/setup.py", line 46, in get_runtime_client_extension
#13 3.672           extra_link_args=get_curl_extra_linker_flags(),
#13 3.672         File "/tmp/pip-install-oq3zcfna/awslambdaric_c7586fb4827e4213ae87abf6af43a2cc/setup.py", line 19, in get_curl_extra_linker_flags
#13 3.672           check_call(["./scripts/preinstall.sh"])
#13 3.672         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
#13 3.672           raise CalledProcessError(retcode, cmd)
#13 3.672       subprocess.CalledProcessError: Command '['./scripts/preinstall.sh']' returned non-zero exit status 127.
#13 3.672       [end of output]

Have you a solution?

thanks a lots

**Comment by nyalpellyomkar07** [comment]
I am also running in the same error when trying to install awslambdaric on Powershell image of Microsoft
